# -*- coding: utf-8 -*-


# NOTE: This file was generated by setup.py . Any changes will be lost!


# Define where all the depacked tools are.
TOOLS=dict({'asciidoc-8.6.3_2': '/home/christoph/.m2/depack/nz.co.methods/asciidoc','gcc-arm-none-eabi-4.5.1_1': '/home/christoph/.m2/depack/org.gnu.gcc/gcc-arm-none-eabi'})
PROJECT_VERSION='1.0'
